from fpdf import FPDF
import pandas as pd

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Institutional Stock Terminal', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by AI - Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(ticker, scores, peer_df):
    """
    Generates a PDF report and returns the binary content.
    """
    pdf = PDF()
    pdf.add_page()
    
    # --- Title Section ---
    pdf.set_font("Arial", "B", 24)
    pdf.cell(0, 15, f"Analysis Report: {ticker}", ln=True, align="C")
    
    # Final Score
    grade = scores.get('final_grade', 'N/A')
    final_score = scores.get('final_score', 0)
    
    pdf.set_font("Arial", "B", 14)
    # Color code text logic could go here, but FPDF simple is B/W usually or RGB.
    pdf.set_text_color(0, 100, 0) if final_score >= 65 else pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 10, f"Recommendation: {grade} ({final_score}/100)", ln=True, align="C")
    pdf.set_text_color(0, 0, 0) # Reset
    
    # --- Score Breakdown ---
    pdf.ln(10)
    pdf.set_font("Arial", "B", 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "12-Tier Scoring Matrix", ln=True, fill=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", "", 12)
    breakdown = scores.get('breakdown', {})
    
    # 2-column layout for scores
    col_width = 90
    row_height = 8
    
    tiers = list(breakdown.items())
    half = len(tiers) // 2 + (len(tiers) % 2)
    
    for i in range(half):
        # Left Col
        t1, s1 = tiers[i]
        pdf.cell(col_width, row_height, f"{t1}: {s1}", border=1)
        
        # Right Col
        if i + half < len(tiers):
            t2, s2 = tiers[i + half]
            pdf.cell(col_width, row_height, f"{t2}: {s2}", border=1, ln=1)
        else:
            pdf.ln(1)
            
    # --- Sector Peers ---
    if not peer_df.empty:
        pdf.ln(10)
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Sector Peer Comparison", ln=True, fill=True)
        pdf.ln(2)
        
        pdf.set_font("Arial", "B", 10)
        # Headers
        cols = ["Ticker", "Price", "P/E", "EV/EBITDA", "Margins"]
        # Filter df to just these if present
        valid_cols = [c for c in cols if c in peer_df.columns]
        
        w = 38
        for col in valid_cols:
            pdf.cell(w, 8, col, 1, 0, 'C', fill=True)
        pdf.ln()
        
        pdf.set_font("Arial", "", 10)
        for _, row in peer_df.iterrows():
            for col in valid_cols:
                val = str(row[col])
                pdf.cell(w, 8, val, 1, 0, 'C')
            pdf.ln()
            
    # --- Disclaimer ---
    pdf.ln(20)
    pdf.set_font("Arial", "I", 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI automated system for informational purposes only. It does not constitute financial advice. Please do your own due diligence before investing.")
    
    return pdf.output(dest='S').encode('latin-1')
